import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:spike_prime_studio/src/codegen/python_gen.dart';
import 'package:spike_prime_studio/src/model/project.dart';
import 'package:spike_prime_studio/src/teach/teach.dart';

void main() {
  test('project json and zip round-trip', () {
    final project = sampleGettingStarted();
    final decoded = ProjectFile.decode(jsonDecode(ProjectFile.encodePretty(project)));
    expect(ProjectFile.encode(decoded), ProjectFile.encode(project));

    final python = generatePython(project);
    final zip = ProjectFile.encodeZip(project, python);
    final fromZip = ProjectFile.decodeBytes(zip, filename: 'drive.spstudio');
    expect(fromZip.name, project.name);
    expect(fromZip.blocks.length, project.blocks.length);
    expect(python, contains('motor_pair.move_for_degrees'));
    expect(python, contains('await runloop.until'));
    expect(python, contains('async def ready'));
    expect(python, contains('runloop.run(main())'));
  });

  test('sample file on disk matches the built-in project', () {
    final file = File('examples/getting_started.spstudio.json');
    expect(file.existsSync(), isTrue, reason: 'run dart run bin/dump_sample.dart');
    final decoded = ProjectFile.decode(jsonDecode(file.readAsStringSync()));
    expect(ProjectFile.encode(decoded), ProjectFile.encode(sampleGettingStarted()));
    final python = File('examples/getting_started.py').readAsStringSync();
    expect(python, generatePython(sampleGettingStarted()));
  });

  test('a single motor block becomes awaited run_for_degrees', () {
    final project = StudioProject(
      id: 'p',
      name: 'spin',
      slot: 0,
      updatedAt: '2026-10-02T00:00:00.000Z',
      blocks: [
        BlockNode(id: 'h', op: 'onStart'),
        BlockNode(
          id: 'm',
          op: 'motorDegrees',
          args: {'port': 'A', 'degrees': '360', 'velocity': '720', 'stop': 'BRAKE'},
        ),
      ],
    );
    expect(
      generatePython(project),
      '''
# Generated by Spike Prime Studio
# Target firmware: SPIKE App 3 MicroPython
# Slot: 0

import motor
import runloop
from hub import port

async def main():
    # when program starts
    await motor.run_for_degrees(port.A, 360, 720, stop=motor.BRAKE)

runloop.run(main())
'''.trimLeft(),
    );
  });

  test('relative teach becomes degrees plus a wait', () {
    final samples = [
      TeachSample(tMs: 0, motorPos: {'A': 0}, motorAbs: {'A': 0}),
      TeachSample(tMs: 100, motorPos: {'A': 0}, motorAbs: {'A': 0}),
      TeachSample(tMs: 200, motorPos: {'A': 30}, motorAbs: {'A': 30}),
      TeachSample(tMs: 300, motorPos: {'A': 80}, motorAbs: {'A': 80}),
      TeachSample(tMs: 800, motorPos: {'A': 80}, motorAbs: {'A': 80}),
    ];
    final blocks = compileTeach(samples, const TeachOptions());
    final move = blocks.singleWhere((block) => block.op == 'motorDegrees');
    expect(move.args['degrees'], '80');
    expect(move.args['velocity'], '400');
    final wait = blocks.singleWhere((block) => block.op == 'wait');
    expect(wait.args['ms'], '500');
    expect(blocks.first.args['text'], contains('not a continuous curve'));
  });

  test('two motors in one stretch become a together block', () {
    final samples = [
      TeachSample(tMs: 0, motorPos: {'A': 0, 'B': 0}, motorAbs: {'A': 0, 'B': 0}),
      TeachSample(tMs: 200, motorPos: {'A': 40, 'B': -20}, motorAbs: {'A': 40, 'B': -20}),
    ];
    final blocks = compileTeach(samples, const TeachOptions(minHoldMs: 1000));
    final together = blocks.singleWhere((block) => block.op == 'together');
    expect(together.body.map((block) => block.args['degrees']), ['40', '-20']);
  });
}
