# Generated by Spike Prime Studio
# Target firmware: SPIKE App 3 MicroPython
# Slot: 0

import color
import color_sensor
import distance_sensor
import motor
import motor_pair
import runloop
from hub import light, light_matrix, port, sound

async def ready():
    light.color(light.POWER, color.BLUE)
    await sound.beep(523, 90, 60)

async def main():
    # when program starts
    # my block ready is defined above
    await ready()
    # Drive forward, then stop the drive if something is close. Edit the ports to match your build.
    motor_pair.pair(motor_pair.PAIR_1, port.A, port.B)
    await motor_pair.move_for_degrees(motor_pair.PAIR_1, 720, 0, velocity=450)
    await runloop.until(lambda: distance_sensor.distance(port.C) < 150, timeout=4000)
    if color_sensor.color(port.D) == color.RED:
        light_matrix.show_image(light_matrix.IMAGE_HAPPY)
    else:
        await runloop.sleep_ms(200)
    _m1 = motor.run_for_degrees(port.A, -180, 300, stop=motor.BRAKE)
    _m2 = motor.run_for_degrees(port.B, -180, 300, stop=motor.BRAKE)
    await _m1
    await _m2
    light_matrix.write('Hi')

runloop.run(main())
