import '../model/catalog.dart';
import '../model/project.dart';

const _header = '''
# Generated by Spike Prime Studio
# Target firmware: SPIKE App 3 MicroPython
''';

String generatePython(StudioProject project) {
  final defs = <BlockNode>[];
  visitBlocks(project.blocks, (node) {
    if (node.op == 'defBlock') defs.add(node);
  });

  final stacks = <List<BlockNode>>[<BlockNode>[]];
  for (final block in project.blocks) {
    if (block.op == 'onStart' && stacks.last.isNotEmpty) {
      stacks.add(<BlockNode>[]);
    }
    stacks.last.add(block);
  }
  stacks.removeWhere((stack) => stack.isEmpty);
  if (stacks.isEmpty) stacks.add(<BlockNode>[]);

  final used = <String>{};
  String unique(String base) {
    var name = base;
    var n = 2;
    while (used.contains(name)) {
      name = '${base}_$n';
      n += 1;
    }
    used.add(name);
    return name;
  }

  final stackNames = <String>[];
  if (stacks.length == 1) {
    stackNames.add(unique('main'));
  } else {
    for (var i = 0; i < stacks.length; i++) {
      stackNames.add(unique('stack_${i + 1}'));
    }
  }

  final blockNames = <String, String>{};
  for (final def in defs) {
    final raw = (def.args['name'] ?? 'my_block').trim();
    final key = raw.isEmpty ? 'my_block' : raw;
    blockNames[key] = unique(pyIdent(key, fallback: 'my_block'));
  }

  final needs = _Needs();
  visitBlocks(project.blocks, (node) => needs.see(node));

  final gen = _Gen(blockNames);
  final buffer = StringBuffer();
  buffer.write(_header.trim());
  buffer.writeln();
  buffer.writeln('# Slot: ${project.slot}');
  buffer.writeln();
  buffer.write(needs.importBlock());
  buffer.writeln();

  for (final def in defs) {
    final raw = (def.args['name'] ?? 'my_block').trim();
    final key = raw.isEmpty ? 'my_block' : raw;
    buffer.write(gen.function(blockNames[key]!, def.body));
    buffer.writeln();
  }
  for (var i = 0; i < stacks.length; i++) {
    buffer.write(gen.function(stackNames[i], stacks[i]));
    buffer.writeln();
  }
  buffer.writeln('runloop.run(${stackNames.map((name) => '$name()').join(', ')})');
  return buffer.toString();
}

void visitBlocks(List<BlockNode> nodes, void Function(BlockNode node) visit) {
  for (final node in nodes) {
    visit(node);
    visitBlocks(node.body, visit);
    visitBlocks(node.alt, visit);
  }
}

String pyIdent(String raw, {String fallback = 'value'}) {
  var text = raw.trim().replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_');
  if (text.isEmpty || RegExp(r'^[0-9]').hasMatch(text)) {
    text = '${fallback}_$text';
  }
  const keywords = {
    'if',
    'else',
    'elif',
    'for',
    'while',
    'def',
    'class',
    'return',
    'lambda',
    'True',
    'False',
    'None',
    'and',
    'or',
    'not',
    'import',
    'from',
    'pass',
    'await',
    'async',
    'with',
    'try',
    'except',
    'in',
    'is',
    'global',
    'break',
    'continue',
  };
  if (keywords.contains(text)) text = '${text}_var';
  return text;
}

class _Needs {
  bool motor = false;
  bool pair = false;
  bool colorSensor = false;
  bool distance = false;
  bool force = false;
  bool color = false;
  bool button = false;
  bool light = false;
  bool matrix = false;
  bool sound = false;
  bool motion = false;
  bool port = false;

  void see(BlockNode node) {
    switch (node.op) {
      case 'motorDegrees':
      case 'motorTime':
      case 'motorAbsolute':
      case 'motorStart':
      case 'motorStop':
        motor = true;
        port = true;
      case 'drive':
        pair = true;
        port = true;
      case 'matrixText':
      case 'matrixImage':
        matrix = true;
      case 'statusLight':
        light = true;
        color = true;
      case 'beep':
        sound = true;
      default:
        break;
    }
    if (node.op == 'waitUntil' || node.op == 'if' || node.op == 'setVar') {
      final sensor = node.op == 'setVar' ? node.args['source'] : node.args['sensor'];
      switch (sensor) {
        case 'color':
          colorSensor = true;
          color = true;
          port = true;
        case 'reflection':
          colorSensor = true;
          port = true;
        case 'distance':
          distance = true;
          port = true;
        case 'force':
        case 'pressed':
          force = true;
          port = true;
        case 'button':
          button = true;
        case 'yaw':
          motion = true;
        default:
          break;
      }
    }
  }

  String importBlock() {
    final lines = <String>[];
    if (color) lines.add('import color');
    if (colorSensor) lines.add('import color_sensor');
    if (distance) lines.add('import distance_sensor');
    if (force) lines.add('import force_sensor');
    if (motor) lines.add('import motor');
    if (pair) lines.add('import motor_pair');
    lines.add('import runloop');
    final hub = <String>[
      if (button) 'button',
      if (light) 'light',
      if (matrix) 'light_matrix',
      if (motion) 'motion_sensor',
      if (port) 'port',
      if (sound) 'sound',
    ];
    if (hub.isNotEmpty) lines.add('from hub import ${hub.join(', ')}');
    return '${lines.join('\n')}\n';
  }
}

class _Gen {
  _Gen(this.blockNames);

  final Map<String, String> blockNames;
  final buffer = StringBuffer();
  int indent = 0;
  int temps = 0;

  String function(String name, List<BlockNode> body) {
    buffer.clear();
    indent = 0;
    line('async def $name():');
    indent = 1;
    emitList(body, allowEmptyPass: true);
    return buffer.toString();
  }

  void emitList(List<BlockNode> nodes, {bool allowEmptyPass = false}) {
    if (nodes.isEmpty) {
      if (allowEmptyPass) line('pass');
      return;
    }
    for (final node in nodes) {
      emit(node);
    }
  }

  void emit(BlockNode node) {
    switch (node.op) {
      case 'onStart':
        line('# when program starts');
      case 'comment':
        emitComment(node.args['text'] ?? '');
      case 'defBlock':
        line('# my block ${node.args['name'] ?? 'my_block'} is defined above');
      case 'motorDegrees':
        line('await ${motorDegreesExpr(node)}');
      case 'motorTime':
        line('await ${motorTimeExpr(node)}');
      case 'motorAbsolute':
        line('await ${motorAbsoluteExpr(node)}');
      case 'motorStart':
        line('motor.run(port.${portOf(node.args['port'])}, ${signed(node.args['velocity'], 0)})');
      case 'motorStop':
        line('motor.stop(port.${portOf(node.args['port'])}, stop=${stopMode(node.args['stop'])})');
      case 'drive':
        line(pairLine(node));
        line('await ${driveExpr(node)}');
      case 'wait':
        line('await runloop.sleep_ms(${asInt(node.args['ms'], 0).clamp(0, 600000)})');
      case 'waitUntil':
        final timeout = asInt(node.args['timeout'], 0);
        final tail = timeout > 0 ? ', timeout=$timeout' : '';
        line('await runloop.until(lambda: ${condition(node)}$tail)');
      case 'repeat':
        line('for _ in range(${asInt(node.args['times'], 1).clamp(0, 100000)}):');
        indent += 1;
        emitList(node.body, allowEmptyPass: true);
        indent -= 1;
      case 'forever':
        line('while True:');
        indent += 1;
        final before = buffer.length;
        emitList(node.body);
        final chunk = buffer.toString().substring(before);
        if (node.body.isEmpty || !chunk.contains('await ')) {
          line('await runloop.sleep_ms(1)');
        }
        indent -= 1;
      case 'if':
        line('if ${condition(node)}:');
        indent += 1;
        emitList(node.body, allowEmptyPass: true);
        indent -= 1;
        if (node.alt.isNotEmpty) {
          line('else:');
          indent += 1;
          emitList(node.alt, allowEmptyPass: true);
          indent -= 1;
        }
      case 'setVar':
        line('${pyIdent(node.args['name'] ?? 'value')} = ${valueExpr(node)}');
      case 'changeVar':
        final name = pyIdent(node.args['name'] ?? 'value');
        line('$name = $name + ${asInt(node.args['delta'], 0)}');
      case 'callBlock':
        final raw = (node.args['name'] ?? 'my_block').trim();
        final name = blockNames[raw] ?? pyIdent(raw.isEmpty ? 'my_block' : raw);
        line('await $name()');
      case 'matrixText':
        line('light_matrix.write(${pyString(node.args['text'] ?? '')})');
      case 'matrixImage':
        line('light_matrix.show_image(light_matrix.${imageName(node.args['image'])})');
      case 'statusLight':
        line('light.color(light.POWER, color.${colorName(node.args['color'])})');
      case 'beep':
        line(
          'await sound.beep(${asInt(node.args['freq'], 440)}, ${asInt(node.args['ms'], 200)}, ${asInt(node.args['volume'], 80).clamp(0, 100)})',
        );
      case 'stopAll':
        line('return');
      case 'together':
        emitTogether(node);
      default:
        line('# skipped unknown block ${node.op}');
    }
  }

  void emitTogether(BlockNode node) {
    if (node.body.isEmpty) {
      line('pass');
      return;
    }
    final joins = <String>[];
    for (final child in node.body) {
      if (child.op == 'drive') {
        line(pairLine(child));
        final temp = nextTemp();
        line('$temp = ${driveExpr(child)}');
        joins.add(temp);
        continue;
      }
      final expr = simpleExpr(child);
      if (expr != null) {
        final temp = nextTemp();
        line('$temp = $expr');
        joins.add(temp);
      } else {
        line('# Nested group runs before the join. Give it a when-program-starts stack to run beside other stacks.');
        emit(child);
      }
    }
    for (final temp in joins) {
      line('await $temp');
    }
  }

  String? simpleExpr(BlockNode node) {
    return switch (node.op) {
      'motorDegrees' => motorDegreesExpr(node),
      'motorTime' => motorTimeExpr(node),
      'motorAbsolute' => motorAbsoluteExpr(node),
      'wait' => 'runloop.sleep_ms(${asInt(node.args['ms'], 0).clamp(0, 600000)})',
      'beep' =>
        'sound.beep(${asInt(node.args['freq'], 440)}, ${asInt(node.args['ms'], 200)}, ${asInt(node.args['volume'], 80).clamp(0, 100)})',
      _ => null,
    };
  }

  String motorDegreesExpr(BlockNode node) {
    final degrees = asInt(node.args['degrees'], 0);
    final velocity = asInt(node.args['velocity'], 100).abs().clamp(1, 2000);
    return 'motor.run_for_degrees(port.${portOf(node.args['port'])}, $degrees, $velocity, stop=${stopMode(node.args['stop'])})';
  }

  String motorTimeExpr(BlockNode node) {
    final ms = asInt(node.args['ms'], 0).clamp(0, 600000);
    final velocity = signed(node.args['velocity'], 100);
    return 'motor.run_for_time(port.${portOf(node.args['port'])}, $ms, $velocity, stop=${stopMode(node.args['stop'])})';
  }

  String motorAbsoluteExpr(BlockNode node) {
    final position = asInt(node.args['position'], 0);
    final velocity = asInt(node.args['velocity'], 100).abs().clamp(1, 2000);
    return 'motor.run_to_absolute_position(port.${portOf(node.args['port'])}, $position, $velocity, direction=${direction(node.args['direction'])})';
  }

  String pairLine(BlockNode node) {
    return 'motor_pair.pair(motor_pair.PAIR_1, port.${portOf(node.args['left'])}, port.${portOf(node.args['right'], fallback: 'B')})';
  }

  String driveExpr(BlockNode node) {
    final velocity = asInt(node.args['velocity'], 360).abs().clamp(1, 2000);
    final steering = asInt(node.args['steering'], 0).clamp(-100, 100);
    final degrees = asInt(node.args['degrees'], 0);
    return 'motor_pair.move_for_degrees(motor_pair.PAIR_1, $degrees, $steering, velocity=$velocity)';
  }

  String condition(BlockNode node) {
    final sensor = node.args['sensor'] ?? 'distance';
    final port = portOf(node.args['port']);
    final op = compare(node.args['op']);
    final value = node.args['value'] ?? '0';
    switch (sensor) {
      case 'color':
        return 'color_sensor.color(port.$port) $op color.${colorName(value)}';
      case 'reflection':
        return 'color_sensor.reflection(port.$port) $op ${asInt(value, 0)}';
      case 'distance':
        return 'distance_sensor.distance(port.$port) $op ${asInt(value, 0)}';
      case 'force':
        return 'force_sensor.force(port.$port) $op ${asInt(value, 0)}';
      case 'pressed':
        return 'force_sensor.pressed(port.$port)';
      case 'button':
        final which = value.toUpperCase() == 'RIGHT' ? 'RIGHT' : 'LEFT';
        return 'button.pressed(button.$which) > 0';
      case 'yaw':
        return 'motion_sensor.tilt_angles()[0] $op ${asInt(value, 0)}';
      case 'variable':
        return '${pyIdent(node.args['subject'] ?? 'x')} $op ${asInt(value, 0)}';
      default:
        return 'False';
    }
  }

  String valueExpr(BlockNode node) {
    final source = node.args['source'] ?? 'number';
    final port = portOf(node.args['port']);
    switch (source) {
      case 'variable':
        return pyIdent(node.args['value'] ?? 'x');
      case 'reflection':
        return 'color_sensor.reflection(port.$port)';
      case 'distance':
        return 'distance_sensor.distance(port.$port)';
      case 'force':
        return 'force_sensor.force(port.$port)';
      case 'color':
        return 'color_sensor.color(port.$port)';
      case 'yaw':
        return 'motion_sensor.tilt_angles()[0]';
      case 'math':
        final left = _mathToken(node.args['value'] ?? '0');
        final right = _mathToken(node.args['right'] ?? '0');
        final op = switch (node.args['math']) {
          'sub' => '-',
          'mul' => '*',
          'div' => '//',
          _ => '+',
        };
        return '$left $op $right';
      default:
        return '${asInt(node.args['value'], 0)}';
    }
  }

  String _mathToken(String raw) {
    final trimmed = raw.trim();
    if (RegExp(r'^-?\d+$').hasMatch(trimmed)) return trimmed;
    return pyIdent(trimmed);
  }

  void emitComment(String text) {
    final lines = text.split('\n');
    if (lines.every((line) => line.trim().isEmpty)) {
      line('#');
      return;
    }
    for (final entry in lines) {
      line('# ${entry.replaceAll('\r', '')}');
    }
  }

  void line(String text) {
    buffer.writeln('${'    ' * indent}$text');
  }

  String nextTemp() {
    temps += 1;
    return '_m$temps';
  }
}

String stopMode(String? raw) {
  return switch (raw) {
    'COAST' => 'motor.COAST',
    'HOLD' => 'motor.HOLD',
    'CONTINUE' => 'motor.CONTINUE',
    'SMART_COAST' => 'motor.SMART_COAST',
    'SMART_BRAKE' => 'motor.SMART_BRAKE',
    _ => 'motor.BRAKE',
  };
}

String direction(String? raw) {
  return switch (raw) {
    'CLOCKWISE' => 'motor.CLOCKWISE',
    'COUNTERCLOCKWISE' => 'motor.COUNTERCLOCKWISE',
    'LONGEST_PATH' => 'motor.LONGEST_PATH',
    _ => 'motor.SHORTEST_PATH',
  };
}

String compare(String? raw) {
  return switch (raw) {
    'neq' => '!=',
    'lt' => '<',
    'gt' => '>',
    'le' => '<=',
    'ge' => '>=',
    _ => '==',
  };
}

String colorName(String? raw) {
  const allowed = {
    'BLACK',
    'MAGENTA',
    'PURPLE',
    'BLUE',
    'AZURE',
    'TURQUOISE',
    'GREEN',
    'YELLOW',
    'ORANGE',
    'RED',
    'WHITE',
  };
  final name = (raw ?? 'RED').trim().toUpperCase();
  return allowed.contains(name) ? name : 'RED';
}

String imageName(String? raw) {
  const allowed = {
    'IMAGE_HAPPY',
    'IMAGE_SMILE',
    'IMAGE_SAD',
    'IMAGE_HEART',
    'IMAGE_YES',
    'IMAGE_NO',
    'IMAGE_ARROW_N',
  };
  final name = raw ?? 'IMAGE_HAPPY';
  return allowed.contains(name) ? name : 'IMAGE_HAPPY';
}

String pyString(String text) {
  final escaped = text.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', ' ').replaceAll('\r', '');
  return "'$escaped'";
}

int signed(String? raw, int fallback) => asInt(raw, fallback);
